apiVersion: v1
items:
- apiVersion: autoscaling/v2beta1
  kind: HorizontalPodAutoscaler
  metadata:
    creationTimestamp: 2019-04-24T14:26:50Z
    name: php-apache
    namespace: default
    resourceVersion: "72814725"
    selfLink: /apis/autoscaling/v2beta1/namespaces/default/horizontalpodautoscalers/php-apache
    uid: ff9b48d8-669c-11e9-8ce9-42010a80005f
  spec:
    maxReplicas: 10
    metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 50
      type: Resource
    minReplicas: 1
    scaleTargetRef:
      apiVersion: extensions/v1beta1
      kind: Deployment
      name: php-apache
  status:
    conditions:
    - lastTransitionTime: 2019-04-24T14:53:18Z
      message: the last scale time was sufficiently old as to warrant a new scale
      reason: ReadyForNewScale
      status: "True"
      type: AbleToScale
    - lastTransitionTime: 2019-04-24T14:27:20Z
      message: the HPA was able to successfully calculate a replica count from cpu
        resource utilization (percentage of request)
      reason: ValidMetricFound
      status: "True"
      type: ScalingActive
    - lastTransitionTime: 2019-04-24T14:47:18Z
      message: the desired replica count is increasing faster than the maximum scale
        rate
      reason: TooFewReplicas
      status: "True"
      type: ScalingLimited
    currentMetrics:
    - resource:
        currentAverageUtilization: 0
        currentAverageValue: "0"
        name: cpu
      type: Resource
    currentReplicas: 1
    desiredReplicas: 1
    lastScaleTime: 2019-04-24T14:48:18Z
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
